[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
python_files = ["test_*.py", "*_test.py", "testing/python/*.py"]

[tool.coverage.run]
include = ["marombei/**"]
omit = ["*/migrations/*", "*/tests/*"]
plugins = ["django_coverage_plugin"]

[tool.ruff]
fix = true
line-length = 96
target-version = "py312"

[tool.ruff.lint]
extend-select = ["E501"]

[tool.ruff.format]
docstring-code-line-length = 88
indent-style = "space"
quote-style = "double"
skip-magic-trailing-comma = true

[tool.ruff.lint.isort]
force-single-line = true
